- name: update repo java nettools
  hosts: servers
  become: yes
  tasks:
  - name: update repo
    ansible.builtin.apt: update_cache=yes force_apt_get=yes
  - name: install openjdk
    ansible.builtin.apt: name=openjdk-8-jre-headless
  - name: install net-tools
    ansible.builtin.apt: name=net-tools


- name: setup-nexus
  hosts: servers
  tasks:
  - name: check nexus is installed
    ansible.builtin.stat:
      path: /opt/nexus
    register: stat_result



  - name: download nexus tar
    become: yes
    ansible.builtin.get_url:
      url: https://download.sonatype.com/nexus/3/nexus-3.60.0-02-unix.tar.gz
      dest: /opt/
    register: download_result


  - name: untar file
    become: yes
    ansible.builtin.unarchive:
      src: "{{download_result.dest}}"
      dest: /opt/
      remote_src: yes
    when: not stat_result.stat.exists


  - name: rename nexus folder and rename
    become: yes
    command: mv /opt/nexus-3.60.0-02 /opt/nexus
    when: not stat_result.stat.exists


- name: setup-nexus
  become: yes
  hosts: servers
  tasks:
  - name: create nexus user and grp
    ansible.builtin.group:
      name: nexus
      state: present

  - name: user
    become: yes
    ansible.builtin.user:
      name: nexus
      group: nexus

  - name: make nexus user owner of nexus directry
    ansible.builtin.file:
      path: /opt/nexus
      state: directory
      owner: nexus
      group: nexus
      recurse: yes

  - name: make nexus user owner of nexus directry
    ansible.builtin.file:
      path: /opt/sonatype-work
      state: directory
      owner: nexus
      group: nexus
      recurse: yes


#- name: start sonatype nexus
#  hosts: servers
#  become: yes
#  tasks:
#  - name: set run_as_nexus_user
#    ansible.builtin.lineinfile:
#      path: /opt/nexus/bin/nexus.rc
#      regexp: '^#run_as_user=""'
#      line: run_as_user="nexus"
#  - name: Start nexus
#    command: /opt/nexus/bin/nexus start
- name: Start nexus with nexus user
  hosts: servers
  become: yes
  become_user: nexus
  become_flags: "-i"
  tasks:
    - name: Set run_as_user nexus
      ansible.builtin.lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"

    - name: Start nexus with correct shell
      shell: /bin/bash -l -c "/opt/nexus/bin/nexus start"



- name: Verify Nexus
  hosts: servers
  become: yes
  tasks:
  - name: check nexus process status
    ansible.builtin.shell: ps aux | grep nexus
    register: app_status
  - ansible.builtin.debug: msg={{app_status.stdout_lines}}

  - name: Wait for a minute
    ansible.builtin.pause:
      minutes: 2

  - name: check netstat
    ansible.builtin.shell: netstat -plnt
    register: app
  - ansible.builtin.debug: msg={{app.stdout_lines}}
